# --- 字体设置 ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# --- 窗口外观 ---
#background_opacity 0.60
# 加上边距，让你的代码不会死贴着屏幕边缘
#dynamic_background_opacity yes
window_padding_width 1
# 隐藏顶部的标题栏（让它看起来更像一个纯粹的生产力工具）
hide_window_decorations no 
# 禁止记录上次关闭时的窗口大小，强制使用设定的行列数
remember_window_size  no 
initial_window_width  100c
initial_window_height 40c

# --- 鼠标与交互 ---
copy_on_select yes  -- 鼠标选中文本自动复制
focus_follows_mouse yes
remember_window_size  no

# --- 快捷键 ---
# 既然你用 Vim，可以把 Kitty 的分屏快捷键也改得顺手点
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
map ctrl+v paste_from_clipboard 
